// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg6IxCTWg7BYBYj2UAk8qHEXrD1l77LI0',
    appId: '1:385263714285:web:e6deb1258c9539e43231e4',
    messagingSenderId: '385263714285',
    projectId: 'chat-app-flutter-6cbcd',
    authDomain: 'chat-app-flutter-6cbcd.firebaseapp.com',
    storageBucket: 'chat-app-flutter-6cbcd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vPxTytoq4Fzd95vHJm_xnyyJPDY_N7s',
    appId: '1:385263714285:android:ad031f540ce7b3313231e4',
    messagingSenderId: '385263714285',
    projectId: 'chat-app-flutter-6cbcd',
    storageBucket: 'chat-app-flutter-6cbcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkJL1RBZrCxWwj8lt3nt_d6h9gCL2p8rs',
    appId: '1:385263714285:ios:5ba2f7d31189cafd3231e4',
    messagingSenderId: '385263714285',
    projectId: 'chat-app-flutter-6cbcd',
    storageBucket: 'chat-app-flutter-6cbcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkJL1RBZrCxWwj8lt3nt_d6h9gCL2p8rs',
    appId: '1:385263714285:ios:5ba2f7d31189cafd3231e4',
    messagingSenderId: '385263714285',
    projectId: 'chat-app-flutter-6cbcd',
    storageBucket: 'chat-app-flutter-6cbcd.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg6IxCTWg7BYBYj2UAk8qHEXrD1l77LI0',
    appId: '1:385263714285:web:20bf5d32e82c1f9b3231e4',
    messagingSenderId: '385263714285',
    projectId: 'chat-app-flutter-6cbcd',
    authDomain: 'chat-app-flutter-6cbcd.firebaseapp.com',
    storageBucket: 'chat-app-flutter-6cbcd.appspot.com',
  );

}